# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181206_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='expiray_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
