# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181220_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('1', '개'), ('2', 'g'), ('3', 'ml')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('1', '저장'), ('2', '대기중'), ('3', '삭제')], default='1', max_length=1),
        ),
    ]
