# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190103_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='count',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='expiray_date',
            new_name='expiry_date',
        ),
    ]
