# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190119_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('irdnt_sn', models.IntegerField()),
                ('irdnt_nm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_how',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('cooking_no', models.IntegerField()),
                ('cooking_dc', models.CharField(max_length=200)),
                ('stre_step_image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('recipe_nm_ko', models.CharField(max_length=200)),
                ('sumry', models.CharField(max_length=200)),
                ('nation_nm', models.CharField(max_length=200)),
                ('cooking_time', models.CharField(max_length=200)),
                ('calorie', models.CharField(max_length=200)),
                ('level_nm', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('det_url', models.CharField(max_length=200)),
            ],
        ),
    ]
