# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_recipe_food_recipe_how_recipe_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe_food',
            options={'ordering': ('irdnt_sn',)},
        ),
        migrations.AlterField(
            model_name='recipe_food',
            name='irdnt_sn',
            field=models.IntegerField(unique=True),
        ),
    ]
