# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190119_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe_how',
            options={'ordering': ('recipe_id',)},
        ),
        migrations.AlterModelOptions(
            name='recipe_info',
            options={'ordering': ('recipe_id',)},
        ),
        migrations.AlterField(
            model_name='recipe_food',
            name='irdnt_nm',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_how',
            name='cooking_dc',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_how',
            name='stre_step_image_url',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='calorie',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='cooking_time',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='det_url',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='img_url',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='level_nm',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='nation_nm',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='recipe_nm_ko',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='sumry',
            field=models.CharField(max_length=800),
        ),
    ]
