# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190119_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_how',
            name='stre_step_image_url',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
