# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190119_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_food',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe_info'),
        ),
        migrations.AlterField(
            model_name='recipe_how',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe_info'),
        ),
    ]
