# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190119_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
