# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190119_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(default='개', max_length=20),
        ),
    ]
