# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190119_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2019, 1, 19)),
        ),
    ]
